from dataclasses import dataclass


@dataclass
class PostData:
    """
    Data generated by kilroy to make a post.

    Attributes:
        x (bool): First version's dummy data.
    """

    x: bool
